### ISSUE TITLE
Write psql dialect

### ISSUE THREAD

**Issue by PumpkinSeed** [PumpkinSeed/sqlfuzz#4]
Write psql dialect and place it in the drivers.

**Comment by srinidhis94** [comment]
Hi, I can pick this up

**Comment by PumpkinSeed** [comment]
@srinidhis94 sure, let me know of you need any help

**Comment by srinidhis94** [comment]
I think the describe field should be part of interface. It changes between between postgres and  mysql. I also felt that using below query would be better.  This query works for both sql and postgres. Although result is different. 

select * from INFORMATION_SCHEMA.COLUMNS where table_name = 'Persons';

```
func Describe(db *sql.DB, table string) ([]FieldDescriptor, error) {
.
.
}
```
Results : 

Postgres :
https://www.postgresql.org/docs/9.5/infoschema-columns.html
MySQL : 
https://www.mssqltips.com/sqlservertutorial/183/informationschemacolumns/#:~:text=The%20INFORMATION_SCHEMA.,that%20is%20in%20the%20database.
What do you think ?

**Comment by srinidhis94** [comment]
Since the schema is different for two tables, we should maybe decide upon some basic things to consider. Ex : Unique, not null, data type, precision, default, cardinality,primary key etc and exclude fields such as auto-increment. This will be updated generic field list. Then, based on generic field list returned from multiple dialects [mysql and postgres to begin with], we can maybe generate data and again insert. With this, the db connection creation, field list generation based on schema will fall into interface implementation. Rest would remain the same.

**Comment by PumpkinSeed** [comment]
_I think the describe field should be part of interface._

Agree, but to keep consistency if you can move the ShowTables from the descriptor as well that would be nice.

_Since the schema is different..._

The base idea behind the field types that it can act as matchable types. Basically it's not the responsibility of this tool to find exact match for all of the SQL types based on dialect, just find a type from the available Field Types what it can use to load data into the database. Field list generation shouldn't have a proper match, just like something which can be a used to load data. So if you moved the describe or schema definition into the interface that would be enough.

 I don't really want to put the actual db connection into the interface, this is why it's just returns the connection string. 
 
 Let me know what you think. :) 

@borosr what do you think?

**Comment by srinidhis94** [comment]
_The base idea behind the field types that it can act as matchable types. Basically it's not the responsibility of this tool to find exact match for all of the SQL types based on dialect, just find a type from the available Field Types what it can use to load data into the database_
Understood. I think this is right. 

_I don't really want to put the actual db connection into the interface, this is why it's just returns the connection string._
We are now thinking of moving show tables and also getting fieldtypes as interfaces. I think it makes sense for interface to execute the query,process results and give a response <Ex : Table list,field types> instead of returning query string, executing query outside < Ex : show tables,describe table> and maybe again have the interface implement a method to process response, as we have seen response structure varying between mysql and postgres. It can be part of MySQL or Postgres structure. We can initialise at the time of object create.

Below, MySQL and Postgres can have db connection associated with them along with flags. Now connection will be invisible at interface level but we'll be able to access connection object in the implementation.
```
func New(f Flags) Driver {
	switch f.Driver {
	case "mysql":
		return MySQL{f: f}
	case "postgres":
		return Postgres{f: f}
	default:
		log.Fatal("Driver not implemented")
		return nil
	}
}
```

**Comment by PumpkinSeed** [comment]
@srinidhis94 The reason of separation of the connector, it's because this repository is a package as well, not just a binary util. Many of our internal tools are using it and the connector should be a separate singleton pattern or we should have control over it. Ex.: connection to different nodes, long-live connection between fuzzes. So this separation is a necessary movement.

**Comment by srinidhis94** [comment]
Hey, I have made some changes.. Wanted to discuss once. I wanted to push it to some feature branch where changes and diff can be shown. But I don't have any access.  Is there any other way where we can discuss the changes ?

**Comment by borosr** [comment]
Hey! What about forking the repo, implement your changes in fork and then send a pr to us?

**Comment by PumpkinSeed** [comment]
@srinidhis94 Checkout this [link](https://mattstauffer.com/blog/how-to-contribute-to-an-open-source-github-project-using-your-own-fork/). If you have any problem contact me on discord: PumpkinSeed#7707

**Comment by srinidhis94** [comment]
Hey, check this out and let me know the comments. 2 major changes are I have removed descriptor, as describing table would vary across db and have made it part of interface. I am using all the fields returned by db to take value decision instead of just the name of the field. Also added format rule in makefile. 
https://github.com/PumpkinSeed/sqlfuzz/pull/13

**Comment by PumpkinSeed** [comment]
Awesome, let me have a bit of time to check these out.
